

drop table easy_document if exists;

create table easy_document (
                               document_id bigint generated by default as IDENTITY,
                               title varchar(100) not null,
                               type ENUM('PRODUCT_PURCHASE', 'EDUCATION_JOIN') not null,
                               content varchar(2000) not null,
                               owner_id varchar(100) not null,
                               document_status ENUM('ING', 'NOT_APPROVED', 'ALL_APPROVED') not null
);

drop table document_approval if exists;

create table document_approval (
                                   approval_seq bigint generated by default as IDENTITY,
                                   user_id varchar(100) not null,
                                   is_approved boolean not null default false,
                                   comment varchar(300),
                                   approval_order integer not null,
                                   document_id bigint not null,
                                   is_confirm boolean not null default false

);

drop table member if exists;

create table member (
                                   member_seq bigint generated by default as IDENTITY,
                                   user_id varchar(100) not null,
                                   member_name varchar not null,
                                   user_pwd varchar(300) not null

);

drop table member_bulk if exists;

create table member_bulk (
                        member_seq bigint generated by default as IDENTITY,
                        user_id varchar(100) not null,
                        member_name varchar not null,
                        user_pwd varchar(300) not null

);